In [24]:
from pathlib import Path
import pandas as pd

In [2]:
file_path = 'data/deft_files/train/t1_biology_0_0.deft'

In [4]:
fp = Path(file_path)

In [7]:
text = fp.read_text().strip()

In [12]:
lines = text.split('\n\n')

In [20]:
data = []
for i,line in enumerate(lines):
    words = line.split('\n')
    for word in words:
        row = word.split('\t')
        row.append(i)
        data.append(row)

In [28]:
labels = ['TOKEN', 'TXT_SOURCE_FILE', 'START_CHAR', 'END_CHAR' ,'TAG', 'TAG_ID', 'ROOT_ID', 'RELATION','SENT']
df = pd.DataFrame(data,columns=labels)

In [36]:
df[0:60]

,TOKEN,TXT_SOURCE_FILE,START_CHAR,END_CHAR,TAG,TAG_ID,ROOT_ID,RELATION,SENT
0,5,data/source_txt/t1_biology_0_0.deft,250,251,O,-1,-1,0,0.0
1,.,data/source_txt/t1_biology_0_0.deft,251,252,O,-1,-1,0,0.0
2,Science,data/source_txt/t1_biology_0_0.deft,253,260,O,-1,-1,0,1.0
3,includes,data/source_txt/t1_biology_0_0.deft,261,269,O,-1,-1,0,1.0
4,such,data/source_txt/t1_biology_0_0.deft,270,274,O,-1,-1,0,1.0
5,diverse,data/source_txt/t1_biology_0_0.deft,275,282,O,-1,-1,0,1.0
6,fields,data/source_txt/t1_biology_0_0.deft,283,289,O,-1,-1,0,1.0
7,as,data/source_txt/t1_biology_0_0.deft,290,292,O,-1,-1,0,1.0
8,astronomy,data/source_txt/t1_biology_0_0.deft,293,302,O,-1,-1,0,1.0
9,",",data/source_txt/t1_biology_0_0.deft,302,303,O,-1,-1,0,1.0
10,biology,data/source_txt/t1_biology_0_0.deft,304,311,O,-1,-1,0,1.0
11,",",data/source_txt/t1_biology_0_0.deft,311,312,O,-1,-1,0,1.0
12,computer,data/source_txt/t1_biology_0_0.deft,313,321,O,-1,-1,0,1.0
13,sciences,data/source_txt/t1_biology_0_0.deft,322,330,O,-1,-1,0,1.0
14,",",data/source_txt/t1_biology_0_0.deft,330,331,O,-1,-1,0,1.0
15,geology,data/source_txt/t1_biology_0_0.deft,332,339,O,-1,-1,0,1.0
16,",",data/source_txt/t1_biology_0_0.deft,339,340,O,-1,-1,0,1.0
17,logic,data/source_txt/t1_biology_0_0.deft,341,346,O,-1,-1,0,1.0
18,",",data/source_txt/t1_biology_0_0.deft,346,347,O,-1,-1,0,1.0
19,physics,data/source_txt/t1_biology_0_0.deft,348,355,O,-1,-1,0,1.0
20,",",data/source_txt/t1_biology_0_0.deft,355,356,O,-1,-1,0,1.0
21,chemistry,data/source_txt/t1_biology_0_0.deft,357,366,O,-1,-1,0,1.0
22,",",data/source_txt/t1_biology_0_0.deft,366,367,O,-1,-1,0,1.0
23,and,data/source_txt/t1_biology_0_0.deft,368,371,O,-1,-1,0,1.0
24,mathematics,data/source_txt/t1_biology_0_0.deft,372,383,O,-1,-1,0,1.0
25,(,data/source_txt/t1_biology_0_0.deft,384,385,O,-1,-1,0,1.0
26,[,data/source_txt/t1_biology_0_0.deft,385,386,O,-1,-1,0,1.0
27,link,data/source_txt/t1_biology_0_0.deft,386,390,O,-1,-1,0,1.0
28,],data/source_txt/t1_biology_0_0.deft,390,391,O,-1,-1,0,1.0
29,),data/source_txt/t1_biology_0_0.deft,391,392,O,-1,-1,0,1.0
30,.,data/source_txt/t1_biology_0_0.deft,392,393,O,-1,-1,0,1.0
31,However,data/source_txt/t1_biology_0_0.deft,402,409,O,-1,-1,0,2.0
32,",",data/source_txt/t1_biology_0_0.deft,409,410,O,-1,-1,0,2.0
33,those,data/source_txt/t1_biology_0_0.deft,411,416,B-Definition,T127,T128,Direct-Defines,2.0
34,fields,data/source_txt/t1_biology_0_0.deft,417,423,I-Definition,T127,T128,Direct-Defines,2.0
35,of,data/source_txt/t1_biology_0_0.deft,424,426,I-Definition,T127,T128,Direct-Defines,2.0
36,science,data/source_txt/t1_biology_0_0.deft,427,434,I-Definition,T127,T128,Direct-Defines,2.0
37,related,data/source_txt/t1_biology_0_0.deft,435,442,I-Definition,T127,T128,Direct-Defines,2.0
38,to,data/source_txt/t1_biology_0_0.deft,443,445,I-Definition,T127,T128,Direct-Defines,2.0
39,the,data/source_txt/t1_biology_0_0.deft,446,449,I-Definition,T127,T128,Direct-Defines,2.0
40,physical,data/source_txt/t1_biology_0_0.deft,450,458,I-Definition,T127,T128,Direct-Defines,2.0
41,world,data/source_txt/t1_biology_0_0.deft,459,464,I-Definition,T127,T128,Direct-Defines,2.0
42,and,data/source_txt/t1_biology_0_0.deft,465,468,I-Definition,T127,T128,Direct-Defines,2.0
43,its,data/source_txt/t1_biology_0_0.deft,469,472,I-Definition,T127,T128,Direct-Defines,2.0
44,phenomena,data/source_txt/t1_biology_0_0.deft,473,482,I-Definition,T127,T128,Direct-Defines,2.0
45,and,data/source_txt/t1_biology_0_0.deft,483,486,I-Definition,T127,T128,Direct-Defines,2.0
46,processes,data/source_txt/t1_biology_0_0.deft,487,496,I-Definition,T127,T128,Direct-Defines,2.0
47,are,data/source_txt/t1_biology_0_0.deft,497,500,O,-1,-1,0,2.0
48,considered,data/source_txt/t1_biology_0_0.deft,501,511,O,-1,-1,0,2.0
49,natural,data/source_txt/t1_biology_0_0.deft,512,519,B-Term,T128,0,0,2.0
50,sciences,data/source_txt/t1_biology_0_0.deft,520,528,I-Term,T128,0,0,2.0
51,.,data/source_txt/t1_biology_0_0.deft,528,529,O,-1,-1,0,2.0
52,Thus,data/source_txt/t1_biology_0_0.deft,536,540,O,-1,-1,0,3.0
53,",",data/source_txt/t1_biology_0_0.deft,540,541,O,-1,-1,0,3.0
54,a,data/source_txt/t1_biology_0_0.deft,542,543,O,-1,-1,0,3.0
55,museum,data/source_txt/t1_biology_0_0.deft,544,550,O,-1,-1,0,3.0
56,of,data/source_txt/t1_biology_0_0.deft,551,553,O,-1,-1,0,3.0
57,natural,data/source_txt/t1_biology_0_0.deft,554,561,O,-1,-1,0,3.0
58,sciences,data/source_txt/t1_biology_0_0.deft,562,570,O,-1,-1,0,3.0
59,might,data/source_txt/t1_biology_0_0.deft,571,576,O,-1,-1,0,3.0